$axure.loadCurrentPage({
  "url":"借款列表页.html",
  "generationDate":new Date(1432630313656.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9639e5f6650d4bbe8feb23da8d143e1e",
    "type":"Axure:Page",
    "name":"借款列表页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6bf9c60b4434436aab5304e0ddd23e64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":23,
              "y":148},
            "size":{
              "width":1351,
              "height":922},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3450b5cd4746c3b831004dcaf87a99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":23,
                  "y":148},
                "size":{
                  "width":1351,
                  "height":922},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u0.png"}},
{
          "id":"78ef3a2a07c045aebcb5517d9a09e4c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF555555},
            "location":{
              "x":23,
              "y":0},
            "size":{
              "width":1351,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c54daa4d166a49c9bf21428199aa3baa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF555555},
                "location":{
                  "x":23,
                  "y":0},
                "size":{
                  "width":1351,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u2.png"}},
{
          "id":"50375ce39c9c4e27913a1da06871a42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFCC00,
              "opacity":1},
            "location":{
              "x":1166,
              "y":12},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c208b223cd34bccab3b5a618e150d93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00,
                  "opacity":1},
                "location":{
                  "x":1166,
                  "y":12},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2703e987fd6340318a2ab379a0205206",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1217,
              "y":12},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9f26546f1c4be3a957638ca48cebda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1217,
                  "y":12},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0479f89950b048f88976015e1ac62601",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":123,
              "y":12},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c56010b75a1844acb8776194c569f83e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":12},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f25e7ff220d40588913cd2ba1e394d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":187,
              "y":6},
            "size":{
              "width":133,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"020d258699f04217a471253f2f53b046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":187,
                  "y":6},
                "size":{
                  "width":133,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa95a71ff1784faca2fb0feab6133a1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":484,
              "y":10},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08f7f2f6d8b64565b11ae1c9ef2e2fc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":484,
                  "y":10},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u12.png"}},
{
          "id":"7911197786fd43cabbd3b2095542071a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":321,
              "y":11},
            "size":{
              "width":84,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a64177510b9b49d4b7bfe4bdbccd3013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":11},
                "size":{
                  "width":84,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b83d3ec11a19460f983fffc3ad285fa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":417,
              "y":11},
            "size":{
              "width":68,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0b150b1e52f42f6b5b8da1c31581dde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":417,
                  "y":11},
                "size":{
                  "width":68,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e064cb9a921244b9ac3bfb9c7e3bbcc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":23,
              "y":38},
            "size":{
              "width":1351,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"020efa3cb0064fd0a0ca07d4aba375be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":23,
                  "y":38},
                "size":{
                  "width":1351,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u18.png"}},
{
          "id":"7999977e24074b5c9b42d99f233c8d4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":121,
              "y":65},
            "size":{
              "width":190,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d5557e6e7224a20bbb86d4b5be8f511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":121,
                  "y":65},
                "size":{
                  "width":190,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u20.png"}},
{
          "id":"06040bd420bf42c28b1fafeaf1e7ac85",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":624,
              "y":85},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15736eecb791465fa3075d608829cee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":85},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a41b8667864d4f098c6237361ea6c43c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":684,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"458dd71198534b2ead7797a980ec3c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":684,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3eb594e746ad43b5ba9572b4ae78487e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":777,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca6e906aa3ff416099d853326bc50248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":777,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a057ab8b52f4c389aad948e35780d00",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":869,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed87a23d0d7c49dfa9e8f9947720e2ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":869,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"263e795f0b6d46069d65cbee7b3f5d2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":962,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf59939bea14ac88d56a7f865bd88cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2f5130c2c084d739ff856d008bd30dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1054,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11df625f5f7246ad8b18f05afb53ffc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1054,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8b038e4d1134cc0b58c78b1b1786328",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1239,
              "y":85},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5a04452a564f2fbb5c30c1d572dded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1239,
                  "y":85},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bec263c809444a58b6cc336822daa037",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1147,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e599e096d01045e7b33eed00240827b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1147,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"124ba3f4b21546f6b306954174b13bcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "location":{
              "x":23,
              "y":144},
            "size":{
              "width":1351,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3efd67850a8469a83749bf1f8c67a84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "location":{
                  "x":23,
                  "y":144},
                "size":{
                  "width":1351,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u38.png"}},
{
          "id":"726742ede4e242cd8369cadf7274617d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":136,
              "y":162},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a07c7c1b087849afa87d6243d6cd896c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":162},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"696018d757c54ef098631b192e4d0114",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":201,
              "y":165},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bad436dbafd74b60a9ac0e362be8fd79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":165},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08d6411ec2824002bd381587742f3654",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":178,
              "y":165},
            "size":{
              "width":21,
              "height":16},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd4d188aba074221a598534996b8b16a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":178,
                  "y":165},
                "size":{
                  "width":21,
                  "height":16},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u44.png"}},
{
          "id":"152768193e8e4cdfa550046884bd381c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":903,
              "y":210},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2df6617f4b44c259924a5653a9147ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":903,
                  "y":210},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"8bc8de3a23a849fdb381333ae0589a13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF02CACA},
            "location":{
              "x":903,
              "y":210},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe0d03e435604c29b0376017f374e3c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF02CACA},
                "location":{
                  "x":903,
                  "y":210},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u48.png"}},
{
          "id":"a760cb80caa04da5af8579b8550dc5d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":991,
              "y":499},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a97607f14a4a40a8bfc1776f9573c0c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":991,
                  "y":499},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 申请资金过桥借款",
                      "target":{
                        "targetType":"page",
                        "url":"申请资金过桥借款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"07b02315d8544c0e8395c49f61c7bb0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":933,
              "y":280},
            "size":{
              "width":177,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8595b0a16c744b59842541747e33a660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":933,
                  "y":280},
                "size":{
                  "width":177,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fcf6b30e0f24aefaabbe3b2a2e1e27a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":933,
              "y":354},
            "size":{
              "width":302,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7673c9ff6bb043dc8238d8d9af89a477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":933,
                  "y":354},
                "size":{
                  "width":302,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc63871a524743df9b771a1b811766dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":136,
              "y":210},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"372d9293f8644ff69a85c90e9470f916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":136,
                  "y":210},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"1325db356dad435db1a86e5a3df71e03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00A1CC},
            "location":{
              "x":136,
              "y":210},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1840e9c96b849eb83a0c62d4c83f0bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00A1CC},
                "location":{
                  "x":136,
                  "y":210},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u58.png"}},
{
          "id":"976a6be8516e4ae6acd0439b1f453918",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":224,
              "y":499},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb93ab8b611e41b7bd97ea2d2bd77364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":224,
                  "y":499},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 申请抵押借款",
                      "target":{
                        "targetType":"page",
                        "url":"申请抵押借款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"520be8a2ff8b40d5b1e7e90200affb48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":166,
              "y":280},
            "size":{
              "width":177,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ffb1e0c42f41dca3b78b70028bb148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":280},
                "size":{
                  "width":177,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80e14f4aca8f4384b1fbe6ec90b35682",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":166,
              "y":354},
            "size":{
              "width":302,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f06b8df87ee8455a8cfbddaa43c4fa26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":354},
                "size":{
                  "width":302,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68d7897fd75f49b6891f2b671fe60906",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":522,
              "y":210},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26184b29adfc4dda8e3b37f9615b9737",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":522,
                  "y":210},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"2531b11cfa7b467d9baa9092348eba64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD62C2C},
            "location":{
              "x":522,
              "y":210},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3de72f04fff424db349dff011bb79a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD62C2C},
                "location":{
                  "x":522,
                  "y":210},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u68.png"}},
{
          "id":"052e4a9dc8174da3ab84f85911b971bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":606,
              "y":499},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7272be687aa4b94b8a3a8c0ca9a3746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":606,
                  "y":499},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 申请信用借款",
                      "target":{
                        "targetType":"page",
                        "url":"申请信用借款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/借款列表页/u70.png"}},
{
          "id":"f18cdb53d8d64c0ba65b4cb49384605a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":552,
              "y":280},
            "size":{
              "width":161,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"905082cacfd64789b3dfcacee6aa9e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":280},
                "size":{
                  "width":161,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce343e80167f4776988ce913b6b2ed4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":552,
              "y":354},
            "size":{
              "width":302,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2162926d8ff4a73a695b7c1818f66a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":354},
                "size":{
                  "width":302,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68d12d15923a4d1a8da43906395e0d99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":136,
              "y":610},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"940164a631aa4d0f9b5f271c4ef6e837",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":136,
                  "y":610},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"b59fd868360e4bfa93ab18f6d7cc3946",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF656A},
            "location":{
              "x":136,
              "y":610},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfc7d93ca9df45428207c79c042cc443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF656A},
                "location":{
                  "x":136,
                  "y":610},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u78.png"}},
{
          "id":"e7faed8d5483459f8e024e7ee49ffc00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":226,
              "y":906},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd4586226d664717bc6d47204337dc1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":226,
                  "y":906},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布净值借款",
                      "target":{
                        "targetType":"page",
                        "url":"发布净值借款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"e2ca82edd5af4e17ba80864637a5230d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":168,
              "y":680},
            "size":{
              "width":267,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24d3126ee78b4547bc8908ef5eb8d635",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":680},
                "size":{
                  "width":267,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"118987b21ba64762b8a8dffd994b5282",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":168,
              "y":754},
            "size":{
              "width":302,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f36bf5ddd4a41b7b726c1e97f712ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":754},
                "size":{
                  "width":302,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"523a3b1e7b8a4391b50441d2decdcdbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":252,
              "y":872},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b41e5cd1d0344b6b6fb48c9ad38b2d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":252,
                  "y":872},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c8194f6b7f14c8281f473078fd035cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":522,
              "y":610},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb959461e4284471967afa9f05518eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":522,
                  "y":610},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"7c9670995971414d9c38710655105fab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":522,
              "y":610},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6d21d2b8aae4416a7c790dd61907f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":522,
                  "y":610},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u90.png"}},
{
          "id":"57b6d247416443c1b4d5305d7bfc28d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":610,
              "y":906},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb76bcd49274528aaf3ff55dfa69a70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":610,
                  "y":906},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布股权担保借款",
                      "target":{
                        "targetType":"page",
                        "url":"发布股权担保借款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/借款列表页/u70.png"}},
{
          "id":"67d6248c71fa4d23bbe4ca777690010a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":555,
              "y":680},
            "size":{
              "width":161,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67fbb1bb1bb34fc09ddd802a38af25ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":555,
                  "y":680},
                "size":{
                  "width":161,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af0cdd8668fd4590a84deb1e77d73eae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":555,
              "y":754},
            "size":{
              "width":302,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e397f12e094b68966886458787342d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":555,
                  "y":754},
                "size":{
                  "width":302,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddfab219c663431e9bc8021830333a58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":632,
              "y":872},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb896567eda64e0582801eb5b711a7e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":632,
                  "y":872},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6bf9c60b4434436aab5304e0ddd23e64":{
      "scriptId":"u0"},
    "5a3450b5cd4746c3b831004dcaf87a99":{
      "scriptId":"u1"},
    "78ef3a2a07c045aebcb5517d9a09e4c8":{
      "scriptId":"u2"},
    "c54daa4d166a49c9bf21428199aa3baa":{
      "scriptId":"u3"},
    "50375ce39c9c4e27913a1da06871a42b":{
      "scriptId":"u4"},
    "7c208b223cd34bccab3b5a618e150d93":{
      "scriptId":"u5"},
    "2703e987fd6340318a2ab379a0205206":{
      "scriptId":"u6"},
    "8e9f26546f1c4be3a957638ca48cebda":{
      "scriptId":"u7"},
    "0479f89950b048f88976015e1ac62601":{
      "scriptId":"u8"},
    "c56010b75a1844acb8776194c569f83e":{
      "scriptId":"u9"},
    "9f25e7ff220d40588913cd2ba1e394d1":{
      "scriptId":"u10"},
    "020d258699f04217a471253f2f53b046":{
      "scriptId":"u11"},
    "aa95a71ff1784faca2fb0feab6133a1f":{
      "scriptId":"u12"},
    "08f7f2f6d8b64565b11ae1c9ef2e2fc1":{
      "scriptId":"u13"},
    "7911197786fd43cabbd3b2095542071a":{
      "scriptId":"u14"},
    "a64177510b9b49d4b7bfe4bdbccd3013":{
      "scriptId":"u15"},
    "b83d3ec11a19460f983fffc3ad285fa2":{
      "scriptId":"u16"},
    "c0b150b1e52f42f6b5b8da1c31581dde":{
      "scriptId":"u17"},
    "e064cb9a921244b9ac3bfb9c7e3bbcc2":{
      "scriptId":"u18"},
    "020efa3cb0064fd0a0ca07d4aba375be":{
      "scriptId":"u19"},
    "7999977e24074b5c9b42d99f233c8d4c":{
      "scriptId":"u20"},
    "3d5557e6e7224a20bbb86d4b5be8f511":{
      "scriptId":"u21"},
    "06040bd420bf42c28b1fafeaf1e7ac85":{
      "scriptId":"u22"},
    "15736eecb791465fa3075d608829cee1":{
      "scriptId":"u23"},
    "a41b8667864d4f098c6237361ea6c43c":{
      "scriptId":"u24"},
    "458dd71198534b2ead7797a980ec3c05":{
      "scriptId":"u25"},
    "3eb594e746ad43b5ba9572b4ae78487e":{
      "scriptId":"u26"},
    "ca6e906aa3ff416099d853326bc50248":{
      "scriptId":"u27"},
    "6a057ab8b52f4c389aad948e35780d00":{
      "scriptId":"u28"},
    "ed87a23d0d7c49dfa9e8f9947720e2ae":{
      "scriptId":"u29"},
    "263e795f0b6d46069d65cbee7b3f5d2b":{
      "scriptId":"u30"},
    "baf59939bea14ac88d56a7f865bd88cd":{
      "scriptId":"u31"},
    "f2f5130c2c084d739ff856d008bd30dc":{
      "scriptId":"u32"},
    "11df625f5f7246ad8b18f05afb53ffc3":{
      "scriptId":"u33"},
    "e8b038e4d1134cc0b58c78b1b1786328":{
      "scriptId":"u34"},
    "8a5a04452a564f2fbb5c30c1d572dded":{
      "scriptId":"u35"},
    "bec263c809444a58b6cc336822daa037":{
      "scriptId":"u36"},
    "e599e096d01045e7b33eed00240827b1":{
      "scriptId":"u37"},
    "124ba3f4b21546f6b306954174b13bcc":{
      "scriptId":"u38"},
    "f3efd67850a8469a83749bf1f8c67a84":{
      "scriptId":"u39"},
    "726742ede4e242cd8369cadf7274617d":{
      "scriptId":"u40"},
    "a07c7c1b087849afa87d6243d6cd896c":{
      "scriptId":"u41"},
    "696018d757c54ef098631b192e4d0114":{
      "scriptId":"u42"},
    "bad436dbafd74b60a9ac0e362be8fd79":{
      "scriptId":"u43"},
    "08d6411ec2824002bd381587742f3654":{
      "scriptId":"u44"},
    "fd4d188aba074221a598534996b8b16a":{
      "scriptId":"u45"},
    "152768193e8e4cdfa550046884bd381c":{
      "scriptId":"u46"},
    "d2df6617f4b44c259924a5653a9147ad":{
      "scriptId":"u47"},
    "8bc8de3a23a849fdb381333ae0589a13":{
      "scriptId":"u48"},
    "fe0d03e435604c29b0376017f374e3c6":{
      "scriptId":"u49"},
    "a760cb80caa04da5af8579b8550dc5d2":{
      "scriptId":"u50"},
    "a97607f14a4a40a8bfc1776f9573c0c7":{
      "scriptId":"u51"},
    "07b02315d8544c0e8395c49f61c7bb0c":{
      "scriptId":"u52"},
    "8595b0a16c744b59842541747e33a660":{
      "scriptId":"u53"},
    "8fcf6b30e0f24aefaabbe3b2a2e1e27a":{
      "scriptId":"u54"},
    "7673c9ff6bb043dc8238d8d9af89a477":{
      "scriptId":"u55"},
    "cc63871a524743df9b771a1b811766dd":{
      "scriptId":"u56"},
    "372d9293f8644ff69a85c90e9470f916":{
      "scriptId":"u57"},
    "1325db356dad435db1a86e5a3df71e03":{
      "scriptId":"u58"},
    "d1840e9c96b849eb83a0c62d4c83f0bc":{
      "scriptId":"u59"},
    "976a6be8516e4ae6acd0439b1f453918":{
      "scriptId":"u60"},
    "bb93ab8b611e41b7bd97ea2d2bd77364":{
      "scriptId":"u61"},
    "520be8a2ff8b40d5b1e7e90200affb48":{
      "scriptId":"u62"},
    "89ffb1e0c42f41dca3b78b70028bb148":{
      "scriptId":"u63"},
    "80e14f4aca8f4384b1fbe6ec90b35682":{
      "scriptId":"u64"},
    "f06b8df87ee8455a8cfbddaa43c4fa26":{
      "scriptId":"u65"},
    "68d7897fd75f49b6891f2b671fe60906":{
      "scriptId":"u66"},
    "26184b29adfc4dda8e3b37f9615b9737":{
      "scriptId":"u67"},
    "2531b11cfa7b467d9baa9092348eba64":{
      "scriptId":"u68"},
    "c3de72f04fff424db349dff011bb79a9":{
      "scriptId":"u69"},
    "052e4a9dc8174da3ab84f85911b971bf":{
      "scriptId":"u70"},
    "c7272be687aa4b94b8a3a8c0ca9a3746":{
      "scriptId":"u71"},
    "f18cdb53d8d64c0ba65b4cb49384605a":{
      "scriptId":"u72"},
    "905082cacfd64789b3dfcacee6aa9e2d":{
      "scriptId":"u73"},
    "ce343e80167f4776988ce913b6b2ed4e":{
      "scriptId":"u74"},
    "b2162926d8ff4a73a695b7c1818f66a6":{
      "scriptId":"u75"},
    "68d12d15923a4d1a8da43906395e0d99":{
      "scriptId":"u76"},
    "940164a631aa4d0f9b5f271c4ef6e837":{
      "scriptId":"u77"},
    "b59fd868360e4bfa93ab18f6d7cc3946":{
      "scriptId":"u78"},
    "dfc7d93ca9df45428207c79c042cc443":{
      "scriptId":"u79"},
    "e7faed8d5483459f8e024e7ee49ffc00":{
      "scriptId":"u80"},
    "fd4586226d664717bc6d47204337dc1c":{
      "scriptId":"u81"},
    "e2ca82edd5af4e17ba80864637a5230d":{
      "scriptId":"u82"},
    "24d3126ee78b4547bc8908ef5eb8d635":{
      "scriptId":"u83"},
    "118987b21ba64762b8a8dffd994b5282":{
      "scriptId":"u84"},
    "5f36bf5ddd4a41b7b726c1e97f712ed9":{
      "scriptId":"u85"},
    "523a3b1e7b8a4391b50441d2decdcdbe":{
      "scriptId":"u86"},
    "2b41e5cd1d0344b6b6fb48c9ad38b2d6":{
      "scriptId":"u87"},
    "5c8194f6b7f14c8281f473078fd035cd":{
      "scriptId":"u88"},
    "bb959461e4284471967afa9f05518eb5":{
      "scriptId":"u89"},
    "7c9670995971414d9c38710655105fab":{
      "scriptId":"u90"},
    "f6d21d2b8aae4416a7c790dd61907f99":{
      "scriptId":"u91"},
    "57b6d247416443c1b4d5305d7bfc28d9":{
      "scriptId":"u92"},
    "cbb76bcd49274528aaf3ff55dfa69a70":{
      "scriptId":"u93"},
    "67d6248c71fa4d23bbe4ca777690010a":{
      "scriptId":"u94"},
    "67fbb1bb1bb34fc09ddd802a38af25ec":{
      "scriptId":"u95"},
    "af0cdd8668fd4590a84deb1e77d73eae":{
      "scriptId":"u96"},
    "28e397f12e094b68966886458787342d":{
      "scriptId":"u97"},
    "ddfab219c663431e9bc8021830333a58":{
      "scriptId":"u98"},
    "eb896567eda64e0582801eb5b711a7e3":{
      "scriptId":"u99"}}});