$axure.loadCurrentPage({
  "url":"申请完成.html",
  "generationDate":new Date(1432630315804.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6801ffc688104abbac68cef472a2694f",
    "type":"Axure:Page",
    "name":"申请完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a0b3a31553a41c4a1b6444876ffdbb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":23,
              "y":148},
            "size":{
              "width":1351,
              "height":1032},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30c7dce994ec44bca154747b9672c8e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":23,
                  "y":148},
                "size":{
                  "width":1351,
                  "height":1032},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布净值借款/u0.png"}},
{
          "id":"2b99944160a2438b92e46cb08a212ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":136,
              "y":162},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ec7da178bad4e718af712ac2353db2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":162},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89186bec9b794c8cb932d9fe388018c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":201,
              "y":165},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd59af828e824495b786b67fbb57e0ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":165},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95c243bb016040c796243d05003513a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":178,
              "y":165},
            "size":{
              "width":21,
              "height":16},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87e511609b314ce4af7fb255f378e69e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":178,
                  "y":165},
                "size":{
                  "width":21,
                  "height":16},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u44.png"}},
{
          "id":"cb86c81e14ce41d98f74a41ada9299bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":136,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"901c39193bda4630b8157e79c530e801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":136,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"eeaec740b02046f48f07b40fdae0db71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF656A},
            "location":{
              "x":136,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62584e4e07ba4cd19b6a222ec62d85bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF656A},
                "location":{
                  "x":136,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u78.png"}},
{
          "id":"da35793ada96413d9bc9e1df0f6a9d0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":903,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcf9445fb45040e89c3cbe0f25163af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":903,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"0204f118f1d64fe19e15b2c5a7e6ed8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":903,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"836b43faa0524936a72b1d7b97594956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":903,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u90.png"}},
{
          "id":"d4e64037130f4156bf790baddcab4556",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":226,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1baff0c407b94d888d45433e009119db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":226,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"1c9b7c76ec5b4aaa959eb04f93dce374",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":168,
              "y":290},
            "size":{
              "width":241,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ce0735cb9f4091b1e9c391292fe4b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":290},
                "size":{
                  "width":241,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b117f39d2bc34c12a5309eb83e43676c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":991,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fba796124ab4774a2ce39923dc81f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":991,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u70.png"}},
{
          "id":"249da07f32a2476897ddab7d4d302891",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":136,
              "y":620},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65efd39ba9c84727bcffccaac28d3567",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":136,
                  "y":620},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"a4796104605a43d992d493ae59aa876f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3AA354},
            "location":{
              "x":136,
              "y":620},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f70c4ba5f24c4151ab98b3a4f1234c2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3AA354},
                "location":{
                  "x":136,
                  "y":620},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u24.png"}},
{
          "id":"b579fab555d947d68a6e373fbc5ed214",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":227,
              "y":927},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d320e67a49fe42d7a419cf94f9f93042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":227,
                  "y":927},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"fcc7481536ff48ccb14836f000296aac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":522,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62a67e97086048ee8ac339ba6739aed6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":522,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"6ec4d896f16a4a5dac34954f3d0243c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00A1CC},
            "location":{
              "x":522,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f96c831615d471991e67128e96ffb1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00A1CC},
                "location":{
                  "x":522,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u58.png"}},
{
          "id":"d02e6aab388843a6bbe270dffedf9aac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":610,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc5b3aed6f3d4339a1c20b4111f68a06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":610,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"869284a9c57d4bf1b31d8d2cdcf6ad63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":526,
              "y":620},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24dd77d9d1ef46058766d73936213fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":526,
                  "y":620},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"849b425c689749a2b59844e960e877a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD62C2C},
            "location":{
              "x":526,
              "y":620},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72cf1e63f1f048eba51141e364ced6e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD62C2C},
                "location":{
                  "x":526,
                  "y":620},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u68.png"}},
{
          "id":"bdc51145e4664ce0986c3e4e077147c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":610,
              "y":927},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f3e987bc533456ebd3f4787e83e7861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":610,
                  "y":927},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u70.png"}},
{
          "id":"e5caac797338471cae66615ec26e5aa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":167,
              "y":690},
            "size":{
              "width":209,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b835b21526664367aefd9ce89a4f43b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":690},
                "size":{
                  "width":209,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bd31ee64fb54ebfb4689b4eab170b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":936,
              "y":290},
            "size":{
              "width":209,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"303c0b098db74bcb8557bed75291b9ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":290},
                "size":{
                  "width":209,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bf938556ece4d578edbdbb9945adcfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":552,
              "y":290},
            "size":{
              "width":97,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95bf9d204cab4fc19d8bcacff548315b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":290},
                "size":{
                  "width":97,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c482139361d44edbfbe2fa7d7d73015",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":556,
              "y":690},
            "size":{
              "width":161,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4609c1635f43c085f6663b26613af1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":690},
                "size":{
                  "width":161,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f3cc771a8444611b78594c033269377",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":168,
              "y":364},
            "size":{
              "width":302,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1634216c157649ebbf2cc473f8c54ce9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":364},
                "size":{
                  "width":302,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7442e4c79c434c408a7d2bb40496452d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":169,
              "y":764},
            "size":{
              "width":290,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d285289835cc4b16ba536b2ee88e1ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":764},
                "size":{
                  "width":290,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d79ab8f15cf4e48a1052f884aae7e29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":936,
              "y":364},
            "size":{
              "width":302,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fab9c66819ed491fb48097d1d64bd45e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":364},
                "size":{
                  "width":302,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a278e13f6094b7184d5766de0c3d7a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":552,
              "y":364},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f58b366fdc364ddaaa01e4aee9ad5583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":364},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a23d6ff6f12492a897c31f11ba08940",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":556,
              "y":764},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"939f1029f3894f13a803ad736eadb08c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":764},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5e092ca15b142648dd117676b21756c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":252,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d1dfa9e4f3b4e27938f71154c4629de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":252,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"107dab01e87e4302ad5bf10487175042",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":636,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"078d63a05a0d4727b851e3403655ec45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7018863d16143e6ae4580c058aba01e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1013,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae23644ad9949cea7193bce46d5fc42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1013,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c77ec34e83e4eeab690c7417b7c75e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":254,
              "y":893},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bfc566e6105431f87f5e4990fb43661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":893},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93fea066651b4f509e0c7943ed6ed1f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":638,
              "y":893},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a94328ff7f9b4c0ba667d4ff251e1ea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":638,
                  "y":893},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"293c676fde3e4373a4a4b4a41f47ebb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF555555},
            "location":{
              "x":23,
              "y":0},
            "size":{
              "width":1351,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c345cfc2cda3479d9c3fdfb07e7cfe47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF555555},
                "location":{
                  "x":23,
                  "y":0},
                "size":{
                  "width":1351,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u2.png"}},
{
          "id":"bfeab9b643b0482c90f1cd9941aca6da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFCC00,
              "opacity":1},
            "location":{
              "x":1166,
              "y":12},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f1c25ad0ec34e3c92d6ec72bfc3602a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00,
                  "opacity":1},
                "location":{
                  "x":1166,
                  "y":12},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bce23be3c53945a0899aede1f433913a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1217,
              "y":12},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4694c3744ce400b8c2f899828ffeeac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1217,
                  "y":12},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d700a4634dc4e2ba58bf0225c7397bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":123,
              "y":12},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55fc3cf5f0654673b0411aeae4f8c808",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":12},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10a97b1d87f84d848f419b598ee0c592",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":187,
              "y":6},
            "size":{
              "width":133,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afaaf395efe447abab0188ad1538d884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":187,
                  "y":6},
                "size":{
                  "width":133,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5768eed0b4b4a1d9ea111451f2752dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":484,
              "y":10},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b06c264f5c5430c8e165679ebca75ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":484,
                  "y":10},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u12.png"}},
{
          "id":"d1f07f77e8d6469ba3b28634153f2636",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":321,
              "y":11},
            "size":{
              "width":84,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb7390e38b7b4b9d9bb35d64e7fb42b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":11},
                "size":{
                  "width":84,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2af98d3dd894b918c8a6692e4ac151c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":417,
              "y":11},
            "size":{
              "width":68,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fec5f5f83cd45e286627c2a901b6123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":417,
                  "y":11},
                "size":{
                  "width":68,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"551275b1c4ac4020b50e99494fee5028",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":23,
              "y":38},
            "size":{
              "width":1351,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1074df8b49cd4792996157a4adced87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":23,
                  "y":38},
                "size":{
                  "width":1351,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u18.png"}},
{
          "id":"fa0dbb46543d4c41802cd6d745753927",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":121,
              "y":65},
            "size":{
              "width":190,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08e35613ec2c47a58f008bc019bafd5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":121,
                  "y":65},
                "size":{
                  "width":190,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u20.png"}},
{
          "id":"7e57a8d7db984a1ca551375fc1043c79",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":624,
              "y":85},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7665be940df64821b611154d3cfb6543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":85},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"839935c9b07041ceac3224a878f17edc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":684,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0894cb4fd2245e1aadcf0ab9cbe5457",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":684,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b09e8cb256984a968e312bd182b16551",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":777,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0124e2a918bb4f4bb5ba8208b50c82a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":777,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24e7da8cded345739cd05185d8e9080b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":869,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2e91427c63c443d9f5de3c2f3ff1124",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":869,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8e97d9531f1415b958d3f41b22aa982",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":962,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f98cb3488b403c8a009f50586a8133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d85017f599a24c46b51f97aceb65100f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1054,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb18069ab9ce414db58b1852ef3f4f93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1054,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c6e26147183441385f5d637736385ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1239,
              "y":85},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daf512635e9d42aa806d14d38c2d1ed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1239,
                  "y":85},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2493ca66273d44c0a211d67d6f9f690a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1147,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b985f1c20bb54f62a16e9af7cba16b76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1147,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dba29ddd1ca047178719ca7a1dea8f15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "location":{
              "x":23,
              "y":144},
            "size":{
              "width":1351,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c311dd11e0834a1ebf0cdbb19f17be76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "location":{
                  "x":23,
                  "y":144},
                "size":{
                  "width":1351,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u38.png"}},
{
          "id":"23c6c4611eb3477886cb18bbc41d818a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xB5333333},
            "location":{
              "x":23,
              "y":0},
            "size":{
              "width":1351,
              "height":1180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78b81f6e897b4eb29c3bbf0c01ccc478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xB5333333},
                "location":{
                  "x":23,
                  "y":0},
                "size":{
                  "width":1351,
                  "height":1180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u106.png"}},
{
          "id":"aa68f0aea9be4806b6aac06c2c6ed52f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":290,
              "y":279},
            "size":{
              "width":590,
              "height":311},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a421dfd4a2e49159cfcbafe6587eda1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":290,
                  "y":279},
                "size":{
                  "width":590,
                  "height":311},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请完成/u108.png"}},
{
          "id":"91aede89d9ef493da75256e9e31f4ff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":855,
              "y":257},
            "size":{
              "width":50,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5af817c04c9b42d7a1e14b038758b089",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":855,
                  "y":257},
                "size":{
                  "width":50,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u110.png"}},
{
          "id":"96d2fcce8e6b4637a994f8e589f56c45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":321,
              "y":303},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be7b15cee3549528290d983fa83167d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":303},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d65945a4792c4b0b80f37349dac2588b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":398,
              "y":364},
            "size":{
              "width":372,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25430864c0ac415c84db1fe4f41a1613",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":398,
                  "y":364},
                "size":{
                  "width":372,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7e21e44aa06463fb02acb9ad5e6064a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "location":{
              "x":440,
              "y":515},
            "size":{
              "width":313,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c8d50c114c74e659bf437e552dd031e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "location":{
                  "x":440,
                  "y":515},
                "size":{
                  "width":313,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 借款列表页",
                      "target":{
                        "targetType":"page",
                        "url":"借款列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/申请抵押借款/u122.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9a0b3a31553a41c4a1b6444876ffdbb7":{
      "scriptId":"u0"},
    "30c7dce994ec44bca154747b9672c8e0":{
      "scriptId":"u1"},
    "2b99944160a2438b92e46cb08a212ed9":{
      "scriptId":"u2"},
    "6ec7da178bad4e718af712ac2353db2c":{
      "scriptId":"u3"},
    "89186bec9b794c8cb932d9fe388018c3":{
      "scriptId":"u4"},
    "cd59af828e824495b786b67fbb57e0ad":{
      "scriptId":"u5"},
    "95c243bb016040c796243d05003513a1":{
      "scriptId":"u6"},
    "87e511609b314ce4af7fb255f378e69e":{
      "scriptId":"u7"},
    "cb86c81e14ce41d98f74a41ada9299bc":{
      "scriptId":"u8"},
    "901c39193bda4630b8157e79c530e801":{
      "scriptId":"u9"},
    "eeaec740b02046f48f07b40fdae0db71":{
      "scriptId":"u10"},
    "62584e4e07ba4cd19b6a222ec62d85bc":{
      "scriptId":"u11"},
    "da35793ada96413d9bc9e1df0f6a9d0e":{
      "scriptId":"u12"},
    "dcf9445fb45040e89c3cbe0f25163af4":{
      "scriptId":"u13"},
    "0204f118f1d64fe19e15b2c5a7e6ed8c":{
      "scriptId":"u14"},
    "836b43faa0524936a72b1d7b97594956":{
      "scriptId":"u15"},
    "d4e64037130f4156bf790baddcab4556":{
      "scriptId":"u16"},
    "1baff0c407b94d888d45433e009119db":{
      "scriptId":"u17"},
    "1c9b7c76ec5b4aaa959eb04f93dce374":{
      "scriptId":"u18"},
    "89ce0735cb9f4091b1e9c391292fe4b5":{
      "scriptId":"u19"},
    "b117f39d2bc34c12a5309eb83e43676c":{
      "scriptId":"u20"},
    "9fba796124ab4774a2ce39923dc81f01":{
      "scriptId":"u21"},
    "249da07f32a2476897ddab7d4d302891":{
      "scriptId":"u22"},
    "65efd39ba9c84727bcffccaac28d3567":{
      "scriptId":"u23"},
    "a4796104605a43d992d493ae59aa876f":{
      "scriptId":"u24"},
    "f70c4ba5f24c4151ab98b3a4f1234c2a":{
      "scriptId":"u25"},
    "b579fab555d947d68a6e373fbc5ed214":{
      "scriptId":"u26"},
    "d320e67a49fe42d7a419cf94f9f93042":{
      "scriptId":"u27"},
    "fcc7481536ff48ccb14836f000296aac":{
      "scriptId":"u28"},
    "62a67e97086048ee8ac339ba6739aed6":{
      "scriptId":"u29"},
    "6ec4d896f16a4a5dac34954f3d0243c7":{
      "scriptId":"u30"},
    "0f96c831615d471991e67128e96ffb1f":{
      "scriptId":"u31"},
    "d02e6aab388843a6bbe270dffedf9aac":{
      "scriptId":"u32"},
    "fc5b3aed6f3d4339a1c20b4111f68a06":{
      "scriptId":"u33"},
    "869284a9c57d4bf1b31d8d2cdcf6ad63":{
      "scriptId":"u34"},
    "24dd77d9d1ef46058766d73936213fba":{
      "scriptId":"u35"},
    "849b425c689749a2b59844e960e877a7":{
      "scriptId":"u36"},
    "72cf1e63f1f048eba51141e364ced6e0":{
      "scriptId":"u37"},
    "bdc51145e4664ce0986c3e4e077147c6":{
      "scriptId":"u38"},
    "7f3e987bc533456ebd3f4787e83e7861":{
      "scriptId":"u39"},
    "e5caac797338471cae66615ec26e5aa9":{
      "scriptId":"u40"},
    "b835b21526664367aefd9ce89a4f43b7":{
      "scriptId":"u41"},
    "2bd31ee64fb54ebfb4689b4eab170b83":{
      "scriptId":"u42"},
    "303c0b098db74bcb8557bed75291b9ce":{
      "scriptId":"u43"},
    "9bf938556ece4d578edbdbb9945adcfb":{
      "scriptId":"u44"},
    "95bf9d204cab4fc19d8bcacff548315b":{
      "scriptId":"u45"},
    "6c482139361d44edbfbe2fa7d7d73015":{
      "scriptId":"u46"},
    "4e4609c1635f43c085f6663b26613af1":{
      "scriptId":"u47"},
    "2f3cc771a8444611b78594c033269377":{
      "scriptId":"u48"},
    "1634216c157649ebbf2cc473f8c54ce9":{
      "scriptId":"u49"},
    "7442e4c79c434c408a7d2bb40496452d":{
      "scriptId":"u50"},
    "d285289835cc4b16ba536b2ee88e1ec8":{
      "scriptId":"u51"},
    "2d79ab8f15cf4e48a1052f884aae7e29":{
      "scriptId":"u52"},
    "fab9c66819ed491fb48097d1d64bd45e":{
      "scriptId":"u53"},
    "2a278e13f6094b7184d5766de0c3d7a0":{
      "scriptId":"u54"},
    "f58b366fdc364ddaaa01e4aee9ad5583":{
      "scriptId":"u55"},
    "7a23d6ff6f12492a897c31f11ba08940":{
      "scriptId":"u56"},
    "939f1029f3894f13a803ad736eadb08c":{
      "scriptId":"u57"},
    "e5e092ca15b142648dd117676b21756c":{
      "scriptId":"u58"},
    "3d1dfa9e4f3b4e27938f71154c4629de":{
      "scriptId":"u59"},
    "107dab01e87e4302ad5bf10487175042":{
      "scriptId":"u60"},
    "078d63a05a0d4727b851e3403655ec45":{
      "scriptId":"u61"},
    "e7018863d16143e6ae4580c058aba01e":{
      "scriptId":"u62"},
    "9ae23644ad9949cea7193bce46d5fc42":{
      "scriptId":"u63"},
    "2c77ec34e83e4eeab690c7417b7c75e0":{
      "scriptId":"u64"},
    "0bfc566e6105431f87f5e4990fb43661":{
      "scriptId":"u65"},
    "93fea066651b4f509e0c7943ed6ed1f1":{
      "scriptId":"u66"},
    "a94328ff7f9b4c0ba667d4ff251e1ea2":{
      "scriptId":"u67"},
    "293c676fde3e4373a4a4b4a41f47ebb4":{
      "scriptId":"u68"},
    "c345cfc2cda3479d9c3fdfb07e7cfe47":{
      "scriptId":"u69"},
    "bfeab9b643b0482c90f1cd9941aca6da":{
      "scriptId":"u70"},
    "2f1c25ad0ec34e3c92d6ec72bfc3602a":{
      "scriptId":"u71"},
    "bce23be3c53945a0899aede1f433913a":{
      "scriptId":"u72"},
    "d4694c3744ce400b8c2f899828ffeeac":{
      "scriptId":"u73"},
    "4d700a4634dc4e2ba58bf0225c7397bf":{
      "scriptId":"u74"},
    "55fc3cf5f0654673b0411aeae4f8c808":{
      "scriptId":"u75"},
    "10a97b1d87f84d848f419b598ee0c592":{
      "scriptId":"u76"},
    "afaaf395efe447abab0188ad1538d884":{
      "scriptId":"u77"},
    "b5768eed0b4b4a1d9ea111451f2752dd":{
      "scriptId":"u78"},
    "0b06c264f5c5430c8e165679ebca75ee":{
      "scriptId":"u79"},
    "d1f07f77e8d6469ba3b28634153f2636":{
      "scriptId":"u80"},
    "eb7390e38b7b4b9d9bb35d64e7fb42b6":{
      "scriptId":"u81"},
    "c2af98d3dd894b918c8a6692e4ac151c":{
      "scriptId":"u82"},
    "2fec5f5f83cd45e286627c2a901b6123":{
      "scriptId":"u83"},
    "551275b1c4ac4020b50e99494fee5028":{
      "scriptId":"u84"},
    "1074df8b49cd4792996157a4adced87d":{
      "scriptId":"u85"},
    "fa0dbb46543d4c41802cd6d745753927":{
      "scriptId":"u86"},
    "08e35613ec2c47a58f008bc019bafd5d":{
      "scriptId":"u87"},
    "7e57a8d7db984a1ca551375fc1043c79":{
      "scriptId":"u88"},
    "7665be940df64821b611154d3cfb6543":{
      "scriptId":"u89"},
    "839935c9b07041ceac3224a878f17edc":{
      "scriptId":"u90"},
    "f0894cb4fd2245e1aadcf0ab9cbe5457":{
      "scriptId":"u91"},
    "b09e8cb256984a968e312bd182b16551":{
      "scriptId":"u92"},
    "0124e2a918bb4f4bb5ba8208b50c82a2":{
      "scriptId":"u93"},
    "24e7da8cded345739cd05185d8e9080b":{
      "scriptId":"u94"},
    "f2e91427c63c443d9f5de3c2f3ff1124":{
      "scriptId":"u95"},
    "b8e97d9531f1415b958d3f41b22aa982":{
      "scriptId":"u96"},
    "35f98cb3488b403c8a009f50586a8133":{
      "scriptId":"u97"},
    "d85017f599a24c46b51f97aceb65100f":{
      "scriptId":"u98"},
    "eb18069ab9ce414db58b1852ef3f4f93":{
      "scriptId":"u99"},
    "0c6e26147183441385f5d637736385ae":{
      "scriptId":"u100"},
    "daf512635e9d42aa806d14d38c2d1ed2":{
      "scriptId":"u101"},
    "2493ca66273d44c0a211d67d6f9f690a":{
      "scriptId":"u102"},
    "b985f1c20bb54f62a16e9af7cba16b76":{
      "scriptId":"u103"},
    "dba29ddd1ca047178719ca7a1dea8f15":{
      "scriptId":"u104"},
    "c311dd11e0834a1ebf0cdbb19f17be76":{
      "scriptId":"u105"},
    "23c6c4611eb3477886cb18bbc41d818a":{
      "scriptId":"u106"},
    "78b81f6e897b4eb29c3bbf0c01ccc478":{
      "scriptId":"u107"},
    "aa68f0aea9be4806b6aac06c2c6ed52f":{
      "scriptId":"u108"},
    "6a421dfd4a2e49159cfcbafe6587eda1":{
      "scriptId":"u109"},
    "91aede89d9ef493da75256e9e31f4ff6":{
      "scriptId":"u110"},
    "5af817c04c9b42d7a1e14b038758b089":{
      "scriptId":"u111"},
    "96d2fcce8e6b4637a994f8e589f56c45":{
      "scriptId":"u112"},
    "0be7b15cee3549528290d983fa83167d":{
      "scriptId":"u113"},
    "d65945a4792c4b0b80f37349dac2588b":{
      "scriptId":"u114"},
    "25430864c0ac415c84db1fe4f41a1613":{
      "scriptId":"u115"},
    "d7e21e44aa06463fb02acb9ad5e6064a":{
      "scriptId":"u116"},
    "1c8d50c114c74e659bf437e552dd031e":{
      "scriptId":"u117"}}});