$axure.loadCurrentPage({
  "url":"申请完成_1.html",
  "generationDate":new Date(1432630316786.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"731becd8481e4859b5f686b7eb0a2c03",
    "type":"Axure:Page",
    "name":"申请完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"759e0c3ca941430cb5bb5c417bbb10bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":23,
              "y":148},
            "size":{
              "width":1351,
              "height":1032},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"433299d7c25c4701b086271fe88b36fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":23,
                  "y":148},
                "size":{
                  "width":1351,
                  "height":1032},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布净值借款/u0.png"}},
{
          "id":"9b7311a8fcb14ae8aaa9baff65e39aab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":136,
              "y":162},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55764b7c7c264e6da2d7df981e07ae1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":162},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65041ead913c4c4f9325961dcf08d8e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":201,
              "y":165},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e76cd1dad4974c8faed58c7a0f850928",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":165},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a3e47fbd2a54a51a1c2e054675f8789",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":178,
              "y":165},
            "size":{
              "width":21,
              "height":16},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ad32d6f70d7412abcab9dbe91eae8ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":178,
                  "y":165},
                "size":{
                  "width":21,
                  "height":16},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u44.png"}},
{
          "id":"b0817f7e98d943cfb82c77f3351cd02e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":136,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cf0a896948e48d38c365347e8ff3d00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":136,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"01cae1d86c814cc292f363d0dbe1116c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF656A},
            "location":{
              "x":136,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a729d36103e41ce9f55551f1da93356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF656A},
                "location":{
                  "x":136,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u78.png"}},
{
          "id":"b7f6e0d460594291b967c7f1a341a5ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":903,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"205c5dbe8bf64582988e9e1efa43f812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":903,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"c9f00c6341ee46c4832352c0a8a8fece",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":903,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e38bd4e60cfb496e82d9f666bc7f43ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":903,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u90.png"}},
{
          "id":"54b6c1b20f1349249ab6094077fd90d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":226,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2fe1ac7e3a644e98fa3acbb05e16af6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":226,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"359d3741c04d42d6b80a26f2f657af95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":168,
              "y":290},
            "size":{
              "width":241,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"527b4d05d7044156987f69664eb62cd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":290},
                "size":{
                  "width":241,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f538e1a545544b16bcff3905b0181c7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":991,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f42b71c6ef416fb53fcae327b4a628",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":991,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u70.png"}},
{
          "id":"5841bb8d5e5544f1b37c174164ea9466",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":136,
              "y":620},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"901baf63c64e46509ab719c4c273b632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":136,
                  "y":620},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"de6bad8a5e704d9c91fb028cdaf4b16d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3AA354},
            "location":{
              "x":136,
              "y":620},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a52c34b7abc44c51b4e6acba31199a8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3AA354},
                "location":{
                  "x":136,
                  "y":620},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u24.png"}},
{
          "id":"f53e389d12524d419e97f8b98e6c195e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":227,
              "y":927},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac7f2100a8cd4fd7a7ec2e37f7e0f7a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":227,
                  "y":927},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"6f40c75276034e3a9fe31174daac58cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":522,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9901f546aa7421dae6c15def91ff751",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":522,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"7dc0433a0c5a46809c93ef754534176c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00A1CC},
            "location":{
              "x":522,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bafe86bc4ca452c9b432d455e6992a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00A1CC},
                "location":{
                  "x":522,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u58.png"}},
{
          "id":"fce628d26b9e4b96b0baf7452b63ae3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":610,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd83d37543e44a6a98412f7662360017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":610,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"ad106d8bda4f4549b2ebe810d858796c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":526,
              "y":620},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368861af280f45e39e7e8911e6a2a1a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":526,
                  "y":620},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"9a4663dabb9c4d25a8b6c17388cdc332",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD62C2C},
            "location":{
              "x":526,
              "y":620},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31eaac7dfa4949c998b44ec0b067a597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD62C2C},
                "location":{
                  "x":526,
                  "y":620},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u68.png"}},
{
          "id":"63390bdcf41e4f6e893a1e9d853c0190",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":610,
              "y":927},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"072a8fdefddb4c85a1690d06780742ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":610,
                  "y":927},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u70.png"}},
{
          "id":"85ec02ad707744e3bb5a467ad3f0665b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":167,
              "y":690},
            "size":{
              "width":209,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f0655e8002149f48ac435c991c77211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":690},
                "size":{
                  "width":209,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22fa7a42e45b463f98259cfd0b8af974",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":936,
              "y":290},
            "size":{
              "width":209,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ebb8e0a833430b98d3ece6016b09d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":290},
                "size":{
                  "width":209,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cf62af7555b47d897398e698372309e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":552,
              "y":290},
            "size":{
              "width":97,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77d98072be56422cb86847cc1a1b957f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":290},
                "size":{
                  "width":97,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59f4d9ddc4a84c02a1ff9261df9fe7c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":556,
              "y":690},
            "size":{
              "width":161,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0826f440cd9a448c9e79a9b8bcd08917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":690},
                "size":{
                  "width":161,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdee8732dcd74bdd92d6fc4c35ede16e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":168,
              "y":364},
            "size":{
              "width":302,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feee17f9994a4425bcef986f9dddb779",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":364},
                "size":{
                  "width":302,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2407d3d431c74703acf64dd5498fec65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":169,
              "y":764},
            "size":{
              "width":290,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e7d0c8701146c0b916e09d352999b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":764},
                "size":{
                  "width":290,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d6dd6c71e044eccaa8ae0771445839f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":936,
              "y":364},
            "size":{
              "width":302,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3a6be1ce2bd4996a064ec0d6169f8d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":364},
                "size":{
                  "width":302,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"132578f0266d4733ba249f1042806a2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":552,
              "y":364},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4b597e02e9847c48bd5817c31df6d34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":364},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c9e0c05a80b4ce7a01310ee1ac1098a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":556,
              "y":764},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc75fb8b93be4a098391c11423e685f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":764},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e6fb49e09684a82b98efd81745cf12d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":252,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e502241e97a948029b45c68088c08ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":252,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3882b20124934408b31511af98fc2598",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":636,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f579e5faa87c4bb6ad852a1cf21623c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05f6cf93f04841ffb59a1729c90a12f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1013,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e95b7e4999f94a96bd920fd20df5c713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1013,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be905deb8829458dbce41ce8f662600b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":254,
              "y":893},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0357dd59245a4629b59f3e6b387527d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":893},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdb8fa42f6c7478c924e454c0c06321b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":638,
              "y":893},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12aa977ac3904611ac5f038448c4cb6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":638,
                  "y":893},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9617c069637345d5b9c88a0909d453be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF555555},
            "location":{
              "x":23,
              "y":0},
            "size":{
              "width":1351,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91c81fb547b04432a33403063aaea20a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF555555},
                "location":{
                  "x":23,
                  "y":0},
                "size":{
                  "width":1351,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u2.png"}},
{
          "id":"41d073f6e67341e29511055cc23d7031",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFCC00,
              "opacity":1},
            "location":{
              "x":1166,
              "y":12},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df9f69c706534fb7be3a2915123f11da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00,
                  "opacity":1},
                "location":{
                  "x":1166,
                  "y":12},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fafd8cbb43c4161894d95656d96977a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1217,
              "y":12},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b691a8ba34ce448ab3ca3e7c77278fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1217,
                  "y":12},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecd4b298a7d2485998ec57f8213d3e42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":123,
              "y":12},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd79754cf0a43c2ac78a5cd729c0719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":12},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c20ba364214743949ada279e0334d06e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":187,
              "y":6},
            "size":{
              "width":133,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36dd3e692cfe4f39822fd9a81c05faa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":187,
                  "y":6},
                "size":{
                  "width":133,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5284ec4220104e42a59a644d631cdcd0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":484,
              "y":10},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0b89ee6c9849e1bb04b969ffaacd55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":484,
                  "y":10},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u12.png"}},
{
          "id":"f064008545a34e31901dcfff97d19102",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":321,
              "y":11},
            "size":{
              "width":84,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2651d031195c449a968b704ce6250092",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":11},
                "size":{
                  "width":84,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71272e8d1657471694263162c181933b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":417,
              "y":11},
            "size":{
              "width":68,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48221cad8ab6444f945965e1db2126e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":417,
                  "y":11},
                "size":{
                  "width":68,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e48c3d879a954b2fabc6c2e0a0f952d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":23,
              "y":38},
            "size":{
              "width":1351,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a8a601a3fbe45fb8626cfe686f2e752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":23,
                  "y":38},
                "size":{
                  "width":1351,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u18.png"}},
{
          "id":"5df852fd8c8c4dee8c28b08a03d640d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":121,
              "y":65},
            "size":{
              "width":190,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5bdd55fa4fc4d16a9e93706783a1d60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":121,
                  "y":65},
                "size":{
                  "width":190,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u20.png"}},
{
          "id":"7bc7d3657c1644c7b4faeea61777311d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":624,
              "y":85},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f29f4f851d6c479a8086fa5ffaae467a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":85},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaa7a42a8b3d424da1d2c9f1c2680127",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":684,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a7ecac1a2e84e529b7fb650c456c350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":684,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfbd79934def4ebb8812d9e7215cc278",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":777,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ed15e7b30449138e3f8cd01ee688ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":777,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"573cd9e20ead4d9e830c8875331e03e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":869,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f6593aec5a49dca1bde8c79db492d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":869,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73d2dd6e0ecd4589a36f58334519524e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":962,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d89fd2acbab4c0a829bf7ae016698ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5931ff3e511c4217b4fa45b70b7e5263",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1054,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e220fbf0db349c0aea0dc31305ab272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1054,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4a3e76bb2d14c499a8f7cf774f86d56",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1239,
              "y":85},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77cc03e37f8e4f61b44f0a95341bac77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1239,
                  "y":85},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12524ffdb47a42abb167fd15662f1516",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1147,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3cb78a20be94596aaf1c86aabc5bb7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1147,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"285326a1078f4988894bb4a4524c5af5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "location":{
              "x":23,
              "y":144},
            "size":{
              "width":1351,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba2655614cff4d5583e99598a4018f2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "location":{
                  "x":23,
                  "y":144},
                "size":{
                  "width":1351,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u38.png"}},
{
          "id":"36147b63b0964ce5b911f4d6606af64f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xB5333333},
            "location":{
              "x":23,
              "y":0},
            "size":{
              "width":1351,
              "height":1180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a44313a2530b4fde9ebe2458ff844337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xB5333333},
                "location":{
                  "x":23,
                  "y":0},
                "size":{
                  "width":1351,
                  "height":1180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u106.png"}},
{
          "id":"9d5c305c77a744e491012323833e94e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":290,
              "y":279},
            "size":{
              "width":590,
              "height":311},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a67f28770fe44ddbabcfb58d21f0d118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":290,
                  "y":279},
                "size":{
                  "width":590,
                  "height":311},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请完成/u108.png"}},
{
          "id":"6d9a34cec32340c49b7952e180e5bd3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":855,
              "y":257},
            "size":{
              "width":50,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f78fa592de3344529a33cdb694512374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":855,
                  "y":257},
                "size":{
                  "width":50,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u110.png"}},
{
          "id":"42e2d9c135644c929274fcff9ff610e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":321,
              "y":303},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39e5f583ba2147fb98ebce341ef4c5b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":303},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bd3632a1cbf433491017b9417ede35a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":398,
              "y":364},
            "size":{
              "width":372,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7473e0675ce4bccb6a95574c7139552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":398,
                  "y":364},
                "size":{
                  "width":372,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c14911960f744978bff947a3eee5ceb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "location":{
              "x":440,
              "y":515},
            "size":{
              "width":313,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e227311723db4d3abbfd8ddf934ca1e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "location":{
                  "x":440,
                  "y":515},
                "size":{
                  "width":313,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 借款列表页",
                      "target":{
                        "targetType":"page",
                        "url":"借款列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/申请抵押借款/u122.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "759e0c3ca941430cb5bb5c417bbb10bf":{
      "scriptId":"u0"},
    "433299d7c25c4701b086271fe88b36fe":{
      "scriptId":"u1"},
    "9b7311a8fcb14ae8aaa9baff65e39aab":{
      "scriptId":"u2"},
    "55764b7c7c264e6da2d7df981e07ae1c":{
      "scriptId":"u3"},
    "65041ead913c4c4f9325961dcf08d8e9":{
      "scriptId":"u4"},
    "e76cd1dad4974c8faed58c7a0f850928":{
      "scriptId":"u5"},
    "9a3e47fbd2a54a51a1c2e054675f8789":{
      "scriptId":"u6"},
    "1ad32d6f70d7412abcab9dbe91eae8ce":{
      "scriptId":"u7"},
    "b0817f7e98d943cfb82c77f3351cd02e":{
      "scriptId":"u8"},
    "0cf0a896948e48d38c365347e8ff3d00":{
      "scriptId":"u9"},
    "01cae1d86c814cc292f363d0dbe1116c":{
      "scriptId":"u10"},
    "2a729d36103e41ce9f55551f1da93356":{
      "scriptId":"u11"},
    "b7f6e0d460594291b967c7f1a341a5ba":{
      "scriptId":"u12"},
    "205c5dbe8bf64582988e9e1efa43f812":{
      "scriptId":"u13"},
    "c9f00c6341ee46c4832352c0a8a8fece":{
      "scriptId":"u14"},
    "e38bd4e60cfb496e82d9f666bc7f43ef":{
      "scriptId":"u15"},
    "54b6c1b20f1349249ab6094077fd90d2":{
      "scriptId":"u16"},
    "b2fe1ac7e3a644e98fa3acbb05e16af6":{
      "scriptId":"u17"},
    "359d3741c04d42d6b80a26f2f657af95":{
      "scriptId":"u18"},
    "527b4d05d7044156987f69664eb62cd5":{
      "scriptId":"u19"},
    "f538e1a545544b16bcff3905b0181c7d":{
      "scriptId":"u20"},
    "52f42b71c6ef416fb53fcae327b4a628":{
      "scriptId":"u21"},
    "5841bb8d5e5544f1b37c174164ea9466":{
      "scriptId":"u22"},
    "901baf63c64e46509ab719c4c273b632":{
      "scriptId":"u23"},
    "de6bad8a5e704d9c91fb028cdaf4b16d":{
      "scriptId":"u24"},
    "a52c34b7abc44c51b4e6acba31199a8e":{
      "scriptId":"u25"},
    "f53e389d12524d419e97f8b98e6c195e":{
      "scriptId":"u26"},
    "ac7f2100a8cd4fd7a7ec2e37f7e0f7a8":{
      "scriptId":"u27"},
    "6f40c75276034e3a9fe31174daac58cc":{
      "scriptId":"u28"},
    "a9901f546aa7421dae6c15def91ff751":{
      "scriptId":"u29"},
    "7dc0433a0c5a46809c93ef754534176c":{
      "scriptId":"u30"},
    "6bafe86bc4ca452c9b432d455e6992a8":{
      "scriptId":"u31"},
    "fce628d26b9e4b96b0baf7452b63ae3e":{
      "scriptId":"u32"},
    "bd83d37543e44a6a98412f7662360017":{
      "scriptId":"u33"},
    "ad106d8bda4f4549b2ebe810d858796c":{
      "scriptId":"u34"},
    "368861af280f45e39e7e8911e6a2a1a0":{
      "scriptId":"u35"},
    "9a4663dabb9c4d25a8b6c17388cdc332":{
      "scriptId":"u36"},
    "31eaac7dfa4949c998b44ec0b067a597":{
      "scriptId":"u37"},
    "63390bdcf41e4f6e893a1e9d853c0190":{
      "scriptId":"u38"},
    "072a8fdefddb4c85a1690d06780742ea":{
      "scriptId":"u39"},
    "85ec02ad707744e3bb5a467ad3f0665b":{
      "scriptId":"u40"},
    "6f0655e8002149f48ac435c991c77211":{
      "scriptId":"u41"},
    "22fa7a42e45b463f98259cfd0b8af974":{
      "scriptId":"u42"},
    "e7ebb8e0a833430b98d3ece6016b09d4":{
      "scriptId":"u43"},
    "4cf62af7555b47d897398e698372309e":{
      "scriptId":"u44"},
    "77d98072be56422cb86847cc1a1b957f":{
      "scriptId":"u45"},
    "59f4d9ddc4a84c02a1ff9261df9fe7c0":{
      "scriptId":"u46"},
    "0826f440cd9a448c9e79a9b8bcd08917":{
      "scriptId":"u47"},
    "cdee8732dcd74bdd92d6fc4c35ede16e":{
      "scriptId":"u48"},
    "feee17f9994a4425bcef986f9dddb779":{
      "scriptId":"u49"},
    "2407d3d431c74703acf64dd5498fec65":{
      "scriptId":"u50"},
    "e5e7d0c8701146c0b916e09d352999b7":{
      "scriptId":"u51"},
    "0d6dd6c71e044eccaa8ae0771445839f":{
      "scriptId":"u52"},
    "c3a6be1ce2bd4996a064ec0d6169f8d8":{
      "scriptId":"u53"},
    "132578f0266d4733ba249f1042806a2c":{
      "scriptId":"u54"},
    "b4b597e02e9847c48bd5817c31df6d34":{
      "scriptId":"u55"},
    "6c9e0c05a80b4ce7a01310ee1ac1098a":{
      "scriptId":"u56"},
    "cc75fb8b93be4a098391c11423e685f5":{
      "scriptId":"u57"},
    "3e6fb49e09684a82b98efd81745cf12d":{
      "scriptId":"u58"},
    "e502241e97a948029b45c68088c08ec7":{
      "scriptId":"u59"},
    "3882b20124934408b31511af98fc2598":{
      "scriptId":"u60"},
    "f579e5faa87c4bb6ad852a1cf21623c2":{
      "scriptId":"u61"},
    "05f6cf93f04841ffb59a1729c90a12f9":{
      "scriptId":"u62"},
    "e95b7e4999f94a96bd920fd20df5c713":{
      "scriptId":"u63"},
    "be905deb8829458dbce41ce8f662600b":{
      "scriptId":"u64"},
    "0357dd59245a4629b59f3e6b387527d1":{
      "scriptId":"u65"},
    "fdb8fa42f6c7478c924e454c0c06321b":{
      "scriptId":"u66"},
    "12aa977ac3904611ac5f038448c4cb6f":{
      "scriptId":"u67"},
    "9617c069637345d5b9c88a0909d453be":{
      "scriptId":"u68"},
    "91c81fb547b04432a33403063aaea20a":{
      "scriptId":"u69"},
    "41d073f6e67341e29511055cc23d7031":{
      "scriptId":"u70"},
    "df9f69c706534fb7be3a2915123f11da":{
      "scriptId":"u71"},
    "3fafd8cbb43c4161894d95656d96977a":{
      "scriptId":"u72"},
    "b691a8ba34ce448ab3ca3e7c77278fba":{
      "scriptId":"u73"},
    "ecd4b298a7d2485998ec57f8213d3e42":{
      "scriptId":"u74"},
    "8cd79754cf0a43c2ac78a5cd729c0719":{
      "scriptId":"u75"},
    "c20ba364214743949ada279e0334d06e":{
      "scriptId":"u76"},
    "36dd3e692cfe4f39822fd9a81c05faa4":{
      "scriptId":"u77"},
    "5284ec4220104e42a59a644d631cdcd0":{
      "scriptId":"u78"},
    "bb0b89ee6c9849e1bb04b969ffaacd55":{
      "scriptId":"u79"},
    "f064008545a34e31901dcfff97d19102":{
      "scriptId":"u80"},
    "2651d031195c449a968b704ce6250092":{
      "scriptId":"u81"},
    "71272e8d1657471694263162c181933b":{
      "scriptId":"u82"},
    "48221cad8ab6444f945965e1db2126e1":{
      "scriptId":"u83"},
    "e48c3d879a954b2fabc6c2e0a0f952d4":{
      "scriptId":"u84"},
    "6a8a601a3fbe45fb8626cfe686f2e752":{
      "scriptId":"u85"},
    "5df852fd8c8c4dee8c28b08a03d640d3":{
      "scriptId":"u86"},
    "c5bdd55fa4fc4d16a9e93706783a1d60":{
      "scriptId":"u87"},
    "7bc7d3657c1644c7b4faeea61777311d":{
      "scriptId":"u88"},
    "f29f4f851d6c479a8086fa5ffaae467a":{
      "scriptId":"u89"},
    "aaa7a42a8b3d424da1d2c9f1c2680127":{
      "scriptId":"u90"},
    "0a7ecac1a2e84e529b7fb650c456c350":{
      "scriptId":"u91"},
    "cfbd79934def4ebb8812d9e7215cc278":{
      "scriptId":"u92"},
    "48ed15e7b30449138e3f8cd01ee688ea":{
      "scriptId":"u93"},
    "573cd9e20ead4d9e830c8875331e03e3":{
      "scriptId":"u94"},
    "57f6593aec5a49dca1bde8c79db492d4":{
      "scriptId":"u95"},
    "73d2dd6e0ecd4589a36f58334519524e":{
      "scriptId":"u96"},
    "6d89fd2acbab4c0a829bf7ae016698ce":{
      "scriptId":"u97"},
    "5931ff3e511c4217b4fa45b70b7e5263":{
      "scriptId":"u98"},
    "3e220fbf0db349c0aea0dc31305ab272":{
      "scriptId":"u99"},
    "a4a3e76bb2d14c499a8f7cf774f86d56":{
      "scriptId":"u100"},
    "77cc03e37f8e4f61b44f0a95341bac77":{
      "scriptId":"u101"},
    "12524ffdb47a42abb167fd15662f1516":{
      "scriptId":"u102"},
    "a3cb78a20be94596aaf1c86aabc5bb7c":{
      "scriptId":"u103"},
    "285326a1078f4988894bb4a4524c5af5":{
      "scriptId":"u104"},
    "ba2655614cff4d5583e99598a4018f2b":{
      "scriptId":"u105"},
    "36147b63b0964ce5b911f4d6606af64f":{
      "scriptId":"u106"},
    "a44313a2530b4fde9ebe2458ff844337":{
      "scriptId":"u107"},
    "9d5c305c77a744e491012323833e94e2":{
      "scriptId":"u108"},
    "a67f28770fe44ddbabcfb58d21f0d118":{
      "scriptId":"u109"},
    "6d9a34cec32340c49b7952e180e5bd3c":{
      "scriptId":"u110"},
    "f78fa592de3344529a33cdb694512374":{
      "scriptId":"u111"},
    "42e2d9c135644c929274fcff9ff610e8":{
      "scriptId":"u112"},
    "39e5f583ba2147fb98ebce341ef4c5b4":{
      "scriptId":"u113"},
    "3bd3632a1cbf433491017b9417ede35a":{
      "scriptId":"u114"},
    "a7473e0675ce4bccb6a95574c7139552":{
      "scriptId":"u115"},
    "c14911960f744978bff947a3eee5ceb1":{
      "scriptId":"u116"},
    "e227311723db4d3abbfd8ddf934ca1e5":{
      "scriptId":"u117"}}});