$axure.loadCurrentPage({
  "url":"申请完成_2.html",
  "generationDate":new Date(1432630317856.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d4cb72d0bc8b4cddacd35ef1596a6e54",
    "type":"Axure:Page",
    "name":"申请完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1535d27964404f4f9c61022281f4b30c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":23,
              "y":148},
            "size":{
              "width":1351,
              "height":1032},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3e8dc3c42f54073b182def237ca0a56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":23,
                  "y":148},
                "size":{
                  "width":1351,
                  "height":1032},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布净值借款/u0.png"}},
{
          "id":"e6b5d5992870477797c0913ead84e940",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":136,
              "y":162},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bc07e646ef2472fb7565cc632b7e01f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":162},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4067139a68945159485949e8f85d0a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":201,
              "y":165},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c7548ac69d44bdab3e6744ac2191c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":165},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a56041f4bcc84b22919301ef02f9f25d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":178,
              "y":165},
            "size":{
              "width":21,
              "height":16},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33ae07ed4320487493597128284e947a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":178,
                  "y":165},
                "size":{
                  "width":21,
                  "height":16},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u44.png"}},
{
          "id":"2fa962348a14451d8e4ddee15a41939b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":136,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82ae2d9af6484db8abfb3a66ea01acc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":136,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"b17f1c29baf44cba979b22aaabf39e5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF656A},
            "location":{
              "x":136,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6273d33730c441ad93980bcd64ad5903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF656A},
                "location":{
                  "x":136,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u78.png"}},
{
          "id":"8c1818a80ca349a1ac85ed8cff21016c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":903,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c5014b057449f29829c4dcb80d95ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":903,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"1ae5cec4ba394873910d406a4462b7e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":903,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93ecc084a2974cb589df96feb3096ba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":903,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u90.png"}},
{
          "id":"be5f3f4d52a24f1a9afcf9683083040f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":226,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6406a94e8a09417b811b675b8202a5d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":226,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"b5f33e623bdf420c8b1f955dc2e49084",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":168,
              "y":290},
            "size":{
              "width":241,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7da12c05a24146dcaecd79540ce6effd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":290},
                "size":{
                  "width":241,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6822581359114c5ba3e95228744426fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":991,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81efff3666f04842b5d3aa39c98ef35c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":991,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u70.png"}},
{
          "id":"c0138f755e9d4019a115594c26f2274a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":136,
              "y":620},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c363f49113d64309b9e123cc7b82564c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":136,
                  "y":620},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"9a06f2cfcf4d47918b6c047135c38ff4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3AA354},
            "location":{
              "x":136,
              "y":620},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4465e22104948d295dfdc410cd15b9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3AA354},
                "location":{
                  "x":136,
                  "y":620},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u24.png"}},
{
          "id":"07c2d29408dd4622837573b088eb5ad9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":227,
              "y":927},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a04cdb41fe4cdebdca84370a19ece4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":227,
                  "y":927},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"222afe0cb97b44c294557c71367c9502",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":522,
              "y":220},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"913a26e5803946218a98ebf8a7d2600a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":522,
                  "y":220},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"8140cc2e7f484a41a87c8c452e67bbb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00A1CC},
            "location":{
              "x":522,
              "y":220},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7095ba1f5fa94687b7e888f43ac12bc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00A1CC},
                "location":{
                  "x":522,
                  "y":220},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u58.png"}},
{
          "id":"3b4a46d2a2b84913b4e2a10c34c9924d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":610,
              "y":527},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcb06bee70204564bbb68d5089e59fcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":610,
                  "y":527},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u50.png"}},
{
          "id":"ecbbe32f1d1e4993a41dd45e1fdce78e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":526,
              "y":620},
            "size":{
              "width":354,
              "height":370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d230a3cf6e7246e8b149bb48d7329dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":526,
                  "y":620},
                "size":{
                  "width":354,
                  "height":370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u46.png"}},
{
          "id":"d873b22ecaa240ecb114fa8f5d1ccd2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD62C2C},
            "location":{
              "x":526,
              "y":620},
            "size":{
              "width":354,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51ca6e90d5044271af952f8b41a00101",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD62C2C},
                "location":{
                  "x":526,
                  "y":620},
                "size":{
                  "width":354,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u68.png"}},
{
          "id":"f578d382b08140229f7efcd5338458fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7181B,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":610,
              "y":927},
            "size":{
              "width":185,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a64ec66cdf0b4058935e06f8ff8c3da1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":610,
                  "y":927},
                "size":{
                  "width":185,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u70.png"}},
{
          "id":"fadd09432a724cc2874d2baad69ae5cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":167,
              "y":690},
            "size":{
              "width":209,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60a9e723424d4d14acae65d43e339486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":167,
                  "y":690},
                "size":{
                  "width":209,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a88c8660a564f8fa7acf709d1db0f9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":936,
              "y":290},
            "size":{
              "width":209,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fb719923f7e44cb81007e1c78ab9e84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":290},
                "size":{
                  "width":209,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13acf3cc655c4e7d8f5cfe09cd660f8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":552,
              "y":290},
            "size":{
              "width":97,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e4a899ca834f47a99e12f3924b3594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":290},
                "size":{
                  "width":97,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d7a3155fea04ad6a25e3ba627559c86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":556,
              "y":690},
            "size":{
              "width":161,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3602c066b1fb40ccb859409aaaa8f362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":690},
                "size":{
                  "width":161,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65bfc516019547bcae479c11a0be611b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":168,
              "y":364},
            "size":{
              "width":302,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a15e5b7308eb426fa8015fd24caff586",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":364},
                "size":{
                  "width":302,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"356c783fc30b4fd289097baa96647f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":169,
              "y":764},
            "size":{
              "width":290,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"151afddd44cf4573aefc79c68da4100c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":764},
                "size":{
                  "width":290,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee4588ec6c234d95aea8b687eb396011",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":936,
              "y":364},
            "size":{
              "width":302,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82505474cce4f7fba427f62fecd6ddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":364},
                "size":{
                  "width":302,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"892b1086012a4c149c101df771a766fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":552,
              "y":364},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f64fd8d48d74da7b41dd1cca63232c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":364},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03f029aeba7248d0bc7e4d8573aa5ac1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":556,
              "y":764},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3c108f15ff64c07a7acccdc1c550ece",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":764},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afb2c51b9f1f4359a99fcb8fea862831",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":252,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"355d21abb8154094995070b1b2e35806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":252,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f210f4a4c314e2aae0dfa99abd93c38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":636,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9df5241009984efdb348a686841821c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d0f1c022c594b0a8610497a7e4622d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1013,
              "y":493},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a549c037a74640fa82dcc11445d4527e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1013,
                  "y":493},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4348484df4f5413da9a74ada29781fbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":254,
              "y":893},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bc9a250f2c748d7a86502a0d49b39ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":893},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"082cf92c57ba4a379c1aad19c0e2b456",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":638,
              "y":893},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38eb7bd4da3c4ae899daf80152538c3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":638,
                  "y":893},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf4f6dcf7fc2478886847354438b4cf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFF555555},
            "location":{
              "x":23,
              "y":0},
            "size":{
              "width":1351,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949d7182692640b399cc1a412de08eb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF555555},
                "location":{
                  "x":23,
                  "y":0},
                "size":{
                  "width":1351,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u2.png"}},
{
          "id":"18be33a32d064883817bc83a5cf7c7c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFCC00,
              "opacity":1},
            "location":{
              "x":1166,
              "y":12},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77c481a6e1404400a2ad363a0d093cb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00,
                  "opacity":1},
                "location":{
                  "x":1166,
                  "y":12},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a2bf7175c9b44d48e8e38ebf684fa5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1217,
              "y":12},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8dda5a74b834892bb2d7bc6c1379329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1217,
                  "y":12},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdeffaf269f141888611214575a09970",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":123,
              "y":12},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92ac57454514522b775cfa81211104c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":12},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37a5c81d578149f392b2cd3e550b03c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":187,
              "y":6},
            "size":{
              "width":133,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3214f49444ac4b5fb7bb5082cb3fa3cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":187,
                  "y":6},
                "size":{
                  "width":133,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ea94bd5d686411e97e6137ad49510c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":484,
              "y":10},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"128a060f5d6f436582cb6e3a0508203a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":484,
                  "y":10},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u12.png"}},
{
          "id":"ee71c62c5ed145e5a52e0486f87155b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":321,
              "y":11},
            "size":{
              "width":84,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4de76a5090b444f7823d23b1031c0c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":11},
                "size":{
                  "width":84,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4f234fec78e4cd3a3a45b1cd0a939bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":417,
              "y":11},
            "size":{
              "width":68,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476602b65e074b2b8f4e8579f4a06fe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":417,
                  "y":11},
                "size":{
                  "width":68,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e68f08ffe8e44d694b39403a3daad3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":23,
              "y":38},
            "size":{
              "width":1351,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"777eeb6f068b48998f4a935ef1c618cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":23,
                  "y":38},
                "size":{
                  "width":1351,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u18.png"}},
{
          "id":"120bf39096a843b58efef235bc3dc776",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":121,
              "y":65},
            "size":{
              "width":190,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3b1ccc0fe1441ab19eff2e6f47a8bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":121,
                  "y":65},
                "size":{
                  "width":190,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u20.png"}},
{
          "id":"d0014fd3166340f7a5a37dabaf448dfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":624,
              "y":85},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e8f1f6035bd45de824b04702b2b2e35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":85},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"952c771144a94a838ce535f6f7dcaf54",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":684,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"130beda5724a4ead9c42a6544bf5240f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":684,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4c4821e96ec4a66a4419a946911730a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":777,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d488aacce92a4dc78edf367d2a546f4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":777,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81535299bc0644cbb1b807f59225d208",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":869,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cfaff950eba4cb29157ecc46c5e9f8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":869,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"423ec8bf78564aa4b7dbea791b4e1a3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":962,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"457eccbb394d4b08927974e1c636c14d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":962,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db7f73d395cb43f6a35db51631c2a97e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1054,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a53eb127c5f04eeb946472113443586a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1054,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0540d61ba93b4f1383a6e26f104ab8e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1239,
              "y":85},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87d7b769e56b41a589079f27cdfe3683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1239,
                  "y":85},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3106778878c24c1c83e000e7767e0d49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF555555,
              "opacity":1},
            "location":{
              "x":1147,
              "y":85},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"798f55ae774841e1b9d6513a26279bbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF555555,
                  "opacity":1},
                "location":{
                  "x":1147,
                  "y":85},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"418d68b7fae445f2b3e447ab24e2d714",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "location":{
              "x":23,
              "y":144},
            "size":{
              "width":1351,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a81ae730586424bae07f3a85ea06f32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "location":{
                  "x":23,
                  "y":144},
                "size":{
                  "width":1351,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/借款列表页/u38.png"}},
{
          "id":"c107e6072459457aaf8215913a26c562",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xB5333333},
            "location":{
              "x":23,
              "y":0},
            "size":{
              "width":1351,
              "height":1180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"216193f0c1984d70bfe047903679097c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xB5333333},
                "location":{
                  "x":23,
                  "y":0},
                "size":{
                  "width":1351,
                  "height":1180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u106.png"}},
{
          "id":"d94fb9e57df74754a6e21eaa9f49f3b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":290,
              "y":279},
            "size":{
              "width":590,
              "height":311},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b3fb7be34cd42678da6ad57748a6d40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":290,
                  "y":279},
                "size":{
                  "width":590,
                  "height":311},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请完成/u108.png"}},
{
          "id":"7ae2851e09e04a2a8814ad6976ceb824",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":855,
              "y":257},
            "size":{
              "width":50,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fa7272ef76b42e095e792f89dec8162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":855,
                  "y":257},
                "size":{
                  "width":50,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/申请抵押借款/u110.png"}},
{
          "id":"994d5f81dd28459b9c2728861cf1091d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":321,
              "y":303},
            "size":{
              "width":129,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aa9a26ba9bc4e1a975a0341a4b6fb84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":303},
                "size":{
                  "width":129,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cd48124c9cf4ab8988ca0bb51cf4f1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":398,
              "y":364},
            "size":{
              "width":372,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b193ab123f841098a366a432ccbb6c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":398,
                  "y":364},
                "size":{
                  "width":372,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f01c4fa15064f5b8715364ddd0b094d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7181B},
            "location":{
              "x":440,
              "y":515},
            "size":{
              "width":313,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"804c58228b0c49e4859b34b8fb9d4565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7181B},
                "location":{
                  "x":440,
                  "y":515},
                "size":{
                  "width":313,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 借款列表页",
                      "target":{
                        "targetType":"page",
                        "url":"借款列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/申请抵押借款/u122.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1535d27964404f4f9c61022281f4b30c":{
      "scriptId":"u0"},
    "d3e8dc3c42f54073b182def237ca0a56":{
      "scriptId":"u1"},
    "e6b5d5992870477797c0913ead84e940":{
      "scriptId":"u2"},
    "2bc07e646ef2472fb7565cc632b7e01f":{
      "scriptId":"u3"},
    "d4067139a68945159485949e8f85d0a3":{
      "scriptId":"u4"},
    "7c7548ac69d44bdab3e6744ac2191c07":{
      "scriptId":"u5"},
    "a56041f4bcc84b22919301ef02f9f25d":{
      "scriptId":"u6"},
    "33ae07ed4320487493597128284e947a":{
      "scriptId":"u7"},
    "2fa962348a14451d8e4ddee15a41939b":{
      "scriptId":"u8"},
    "82ae2d9af6484db8abfb3a66ea01acc1":{
      "scriptId":"u9"},
    "b17f1c29baf44cba979b22aaabf39e5c":{
      "scriptId":"u10"},
    "6273d33730c441ad93980bcd64ad5903":{
      "scriptId":"u11"},
    "8c1818a80ca349a1ac85ed8cff21016c":{
      "scriptId":"u12"},
    "69c5014b057449f29829c4dcb80d95ef":{
      "scriptId":"u13"},
    "1ae5cec4ba394873910d406a4462b7e1":{
      "scriptId":"u14"},
    "93ecc084a2974cb589df96feb3096ba6":{
      "scriptId":"u15"},
    "be5f3f4d52a24f1a9afcf9683083040f":{
      "scriptId":"u16"},
    "6406a94e8a09417b811b675b8202a5d7":{
      "scriptId":"u17"},
    "b5f33e623bdf420c8b1f955dc2e49084":{
      "scriptId":"u18"},
    "7da12c05a24146dcaecd79540ce6effd":{
      "scriptId":"u19"},
    "6822581359114c5ba3e95228744426fd":{
      "scriptId":"u20"},
    "81efff3666f04842b5d3aa39c98ef35c":{
      "scriptId":"u21"},
    "c0138f755e9d4019a115594c26f2274a":{
      "scriptId":"u22"},
    "c363f49113d64309b9e123cc7b82564c":{
      "scriptId":"u23"},
    "9a06f2cfcf4d47918b6c047135c38ff4":{
      "scriptId":"u24"},
    "d4465e22104948d295dfdc410cd15b9d":{
      "scriptId":"u25"},
    "07c2d29408dd4622837573b088eb5ad9":{
      "scriptId":"u26"},
    "10a04cdb41fe4cdebdca84370a19ece4":{
      "scriptId":"u27"},
    "222afe0cb97b44c294557c71367c9502":{
      "scriptId":"u28"},
    "913a26e5803946218a98ebf8a7d2600a":{
      "scriptId":"u29"},
    "8140cc2e7f484a41a87c8c452e67bbb5":{
      "scriptId":"u30"},
    "7095ba1f5fa94687b7e888f43ac12bc3":{
      "scriptId":"u31"},
    "3b4a46d2a2b84913b4e2a10c34c9924d":{
      "scriptId":"u32"},
    "fcb06bee70204564bbb68d5089e59fcf":{
      "scriptId":"u33"},
    "ecbbe32f1d1e4993a41dd45e1fdce78e":{
      "scriptId":"u34"},
    "d230a3cf6e7246e8b149bb48d7329dc3":{
      "scriptId":"u35"},
    "d873b22ecaa240ecb114fa8f5d1ccd2d":{
      "scriptId":"u36"},
    "51ca6e90d5044271af952f8b41a00101":{
      "scriptId":"u37"},
    "f578d382b08140229f7efcd5338458fa":{
      "scriptId":"u38"},
    "a64ec66cdf0b4058935e06f8ff8c3da1":{
      "scriptId":"u39"},
    "fadd09432a724cc2874d2baad69ae5cd":{
      "scriptId":"u40"},
    "60a9e723424d4d14acae65d43e339486":{
      "scriptId":"u41"},
    "6a88c8660a564f8fa7acf709d1db0f9c":{
      "scriptId":"u42"},
    "9fb719923f7e44cb81007e1c78ab9e84":{
      "scriptId":"u43"},
    "13acf3cc655c4e7d8f5cfe09cd660f8b":{
      "scriptId":"u44"},
    "59e4a899ca834f47a99e12f3924b3594":{
      "scriptId":"u45"},
    "8d7a3155fea04ad6a25e3ba627559c86":{
      "scriptId":"u46"},
    "3602c066b1fb40ccb859409aaaa8f362":{
      "scriptId":"u47"},
    "65bfc516019547bcae479c11a0be611b":{
      "scriptId":"u48"},
    "a15e5b7308eb426fa8015fd24caff586":{
      "scriptId":"u49"},
    "356c783fc30b4fd289097baa96647f49":{
      "scriptId":"u50"},
    "151afddd44cf4573aefc79c68da4100c":{
      "scriptId":"u51"},
    "ee4588ec6c234d95aea8b687eb396011":{
      "scriptId":"u52"},
    "f82505474cce4f7fba427f62fecd6ddb":{
      "scriptId":"u53"},
    "892b1086012a4c149c101df771a766fa":{
      "scriptId":"u54"},
    "5f64fd8d48d74da7b41dd1cca63232c8":{
      "scriptId":"u55"},
    "03f029aeba7248d0bc7e4d8573aa5ac1":{
      "scriptId":"u56"},
    "d3c108f15ff64c07a7acccdc1c550ece":{
      "scriptId":"u57"},
    "afb2c51b9f1f4359a99fcb8fea862831":{
      "scriptId":"u58"},
    "355d21abb8154094995070b1b2e35806":{
      "scriptId":"u59"},
    "7f210f4a4c314e2aae0dfa99abd93c38":{
      "scriptId":"u60"},
    "9df5241009984efdb348a686841821c5":{
      "scriptId":"u61"},
    "0d0f1c022c594b0a8610497a7e4622d1":{
      "scriptId":"u62"},
    "a549c037a74640fa82dcc11445d4527e":{
      "scriptId":"u63"},
    "4348484df4f5413da9a74ada29781fbd":{
      "scriptId":"u64"},
    "0bc9a250f2c748d7a86502a0d49b39ca":{
      "scriptId":"u65"},
    "082cf92c57ba4a379c1aad19c0e2b456":{
      "scriptId":"u66"},
    "38eb7bd4da3c4ae899daf80152538c3f":{
      "scriptId":"u67"},
    "bf4f6dcf7fc2478886847354438b4cf6":{
      "scriptId":"u68"},
    "949d7182692640b399cc1a412de08eb6":{
      "scriptId":"u69"},
    "18be33a32d064883817bc83a5cf7c7c0":{
      "scriptId":"u70"},
    "77c481a6e1404400a2ad363a0d093cb8":{
      "scriptId":"u71"},
    "8a2bf7175c9b44d48e8e38ebf684fa5a":{
      "scriptId":"u72"},
    "a8dda5a74b834892bb2d7bc6c1379329":{
      "scriptId":"u73"},
    "bdeffaf269f141888611214575a09970":{
      "scriptId":"u74"},
    "d92ac57454514522b775cfa81211104c":{
      "scriptId":"u75"},
    "37a5c81d578149f392b2cd3e550b03c7":{
      "scriptId":"u76"},
    "3214f49444ac4b5fb7bb5082cb3fa3cc":{
      "scriptId":"u77"},
    "4ea94bd5d686411e97e6137ad49510c0":{
      "scriptId":"u78"},
    "128a060f5d6f436582cb6e3a0508203a":{
      "scriptId":"u79"},
    "ee71c62c5ed145e5a52e0486f87155b6":{
      "scriptId":"u80"},
    "4de76a5090b444f7823d23b1031c0c5f":{
      "scriptId":"u81"},
    "c4f234fec78e4cd3a3a45b1cd0a939bb":{
      "scriptId":"u82"},
    "476602b65e074b2b8f4e8579f4a06fe5":{
      "scriptId":"u83"},
    "3e68f08ffe8e44d694b39403a3daad3e":{
      "scriptId":"u84"},
    "777eeb6f068b48998f4a935ef1c618cb":{
      "scriptId":"u85"},
    "120bf39096a843b58efef235bc3dc776":{
      "scriptId":"u86"},
    "5a3b1ccc0fe1441ab19eff2e6f47a8bb":{
      "scriptId":"u87"},
    "d0014fd3166340f7a5a37dabaf448dfb":{
      "scriptId":"u88"},
    "2e8f1f6035bd45de824b04702b2b2e35":{
      "scriptId":"u89"},
    "952c771144a94a838ce535f6f7dcaf54":{
      "scriptId":"u90"},
    "130beda5724a4ead9c42a6544bf5240f":{
      "scriptId":"u91"},
    "b4c4821e96ec4a66a4419a946911730a":{
      "scriptId":"u92"},
    "d488aacce92a4dc78edf367d2a546f4a":{
      "scriptId":"u93"},
    "81535299bc0644cbb1b807f59225d208":{
      "scriptId":"u94"},
    "9cfaff950eba4cb29157ecc46c5e9f8f":{
      "scriptId":"u95"},
    "423ec8bf78564aa4b7dbea791b4e1a3c":{
      "scriptId":"u96"},
    "457eccbb394d4b08927974e1c636c14d":{
      "scriptId":"u97"},
    "db7f73d395cb43f6a35db51631c2a97e":{
      "scriptId":"u98"},
    "a53eb127c5f04eeb946472113443586a":{
      "scriptId":"u99"},
    "0540d61ba93b4f1383a6e26f104ab8e6":{
      "scriptId":"u100"},
    "87d7b769e56b41a589079f27cdfe3683":{
      "scriptId":"u101"},
    "3106778878c24c1c83e000e7767e0d49":{
      "scriptId":"u102"},
    "798f55ae774841e1b9d6513a26279bbf":{
      "scriptId":"u103"},
    "418d68b7fae445f2b3e447ab24e2d714":{
      "scriptId":"u104"},
    "7a81ae730586424bae07f3a85ea06f32":{
      "scriptId":"u105"},
    "c107e6072459457aaf8215913a26c562":{
      "scriptId":"u106"},
    "216193f0c1984d70bfe047903679097c":{
      "scriptId":"u107"},
    "d94fb9e57df74754a6e21eaa9f49f3b3":{
      "scriptId":"u108"},
    "9b3fb7be34cd42678da6ad57748a6d40":{
      "scriptId":"u109"},
    "7ae2851e09e04a2a8814ad6976ceb824":{
      "scriptId":"u110"},
    "7fa7272ef76b42e095e792f89dec8162":{
      "scriptId":"u111"},
    "994d5f81dd28459b9c2728861cf1091d":{
      "scriptId":"u112"},
    "7aa9a26ba9bc4e1a975a0341a4b6fb84":{
      "scriptId":"u113"},
    "9cd48124c9cf4ab8988ca0bb51cf4f1d":{
      "scriptId":"u114"},
    "1b193ab123f841098a366a432ccbb6c7":{
      "scriptId":"u115"},
    "4f01c4fa15064f5b8715364ddd0b094d":{
      "scriptId":"u116"},
    "804c58228b0c49e4859b34b8fb9d4565":{
      "scriptId":"u117"}}});